//go:build ignore

package main

import (
	"bytes"
	"cmp"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"log"
	"os"
	"slices"
	"strings"
	"text/template"

	"github.com/t14raptor/go-fast/ast/internal/astgen"
)

type NodeType int

const (
	NodeTypeStruct NodeType = iota
	NodeTypeSlice
)

type CloneableNodeType struct {
	Type     NodeType
	Name     string
	Children []Child

	IsUnion        bool
	Variants       []astgen.UnionVariant
	KindPrefix     string
	ConstructorSfx string
}

func (n CloneableNodeType) IsSlice() bool { return n.Type == NodeTypeSlice }

type CloneableInterface struct {
	Name       string
	UniqueFunc string
	Structs    []string
}

type Child struct {
	FieldName string
	FieldType string
	Cloneable bool
	Pointer   bool
	Optional  bool
	Interface *CloneableInterface
}

func newChild(fieldName, fieldType string, cloneable, pointer, optional bool) Child {
	return Child{FieldName: fieldName, FieldType: fieldType, Cloneable: cloneable, Pointer: pointer, Optional: optional}
}

// fieldValue returns the expression assigned to a struct field in the cloned
// literal. Optional and interface children stage their value in a preamble
// variable (see the template); the rest are inlined.
func fieldValue(c Child) string {
	switch {
	case !c.Cloneable:
		return "n." + c.FieldName
	case c.Interface != nil:
		return "cloned" + c.Interface.Name
	case c.Optional:
		return strings.ToLower(c.FieldName)
	case c.Pointer:
		return "n." + c.FieldName + ".Clone()"
	default:
		return "*n." + c.FieldName + ".Clone()"
	}
}

// cloneFields renders the comma-separated `Field: value` list for a struct's
// cloned literal. gofmt collapses the surrounding whitespace.
func cloneFields(n CloneableNodeType) string {
	parts := make([]string, len(n.Children))
	for i, c := range n.Children {
		parts[i] = c.FieldName + ": " + fieldValue(c)
	}
	return strings.Join(parts, ", ")
}

func main() {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, "./ast", func(info fs.FileInfo) bool {
		return info.Name() != "clone.go" && info.Name() != "visit.go"
	}, parser.ParseComments)
	if err != nil {
		log.Fatalf("%v", err)
	}

	specs := astgen.FindUnionSpecs(pkgs["ast"].Files)
	var nodes []CloneableNodeType
	var interfaces []CloneableInterface
	for _, file := range pkgs["ast"].Files {
		nodes = append(nodes, findCloneableNodes(file, specs)...)
		interfaces = append(interfaces, findCloneableInterfaces(file)...)
	}
	for _, file := range pkgs["ast"].Files {
		findStructsForInterfaces(file, interfaces)
	}

	slices.SortFunc(nodes, func(a, b CloneableNodeType) int {
		return cmp.Compare(a.Name, b.Name)
	})
	for i := range nodes {
		for j := range nodes[i].Children {
			if idx := slices.IndexFunc(interfaces, func(a CloneableInterface) bool {
				return a.Name == nodes[i].Children[j].FieldType
			}); idx != -1 {
				nodes[i].Children[j].Interface = &interfaces[idx]
			}
		}
	}
	for _, i := range interfaces {
		slices.SortFunc(i.Structs, func(a, b string) int {
			return cmp.Compare(a, b)
		})
	}

	var buf bytes.Buffer
	if err := cloneTemplate.Execute(&buf, nodes); err != nil {
		log.Fatalf("template error: %v", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		os.WriteFile("ast/clone.go", buf.Bytes(), 0644)
		log.Fatalf("format error: %v", err)
	}
	os.WriteFile("ast/clone.go", formatted, 0644)
}

var cloneTemplate = template.Must(template.New("clone").Funcs(template.FuncMap{
	"fieldValue":  fieldValue,
	"cloneFields": cloneFields,
	"toLower":     strings.ToLower,
	"lowerFirst":  func(s string) string { return strings.ToLower(s[:1]) + s[1:] },
}).Parse(`// Code generated by gen_clone.go; DO NOT EDIT.
package ast
{{range .}}{{if not .IsUnion}}
func (n *{{.Name}}) Clone() *{{.Name}} {
{{- if .IsSlice}}
	ns := make({{.Name}}, len(*n))
	for i := range *n {
		ns[i] = *(*n)[i].Clone()
	}
	return &ns
{{- else}}
{{- range .Children}}
{{- if .Interface}}
{{- $intf := .Interface}}
	var cloned{{$intf.Name}} {{$intf.Name}}
	switch {{lowerFirst $intf.Name}} := n.{{.FieldName}}.(type) {
{{- range $intf.Structs}}
	case *{{.}}:
		cloned{{$intf.Name}} = {{lowerFirst $intf.Name}}.Clone()
{{- end}}
	}
{{- else if and .Cloneable .Optional}}
	var {{toLower .FieldName}} *{{.FieldType}}
	if n.{{.FieldName}} != nil {
		{{toLower .FieldName}} = n.{{.FieldName}}.Clone()
	}
{{- end}}
{{- end}}
	return &{{.Name}}{ {{cloneFields .}} }
{{- end}}
}
{{- end}}{{end}}
{{- range .}}{{if .IsUnion}}

func (n *{{.Name}}) Clone() *{{.Name}} {
	switch n.kind {
{{- $kp := .KindPrefix}}{{$sfx := .ConstructorSfx}}{{range .Variants}}
	case {{$kp}}{{.ShortName}}:
		c := (*{{.TypeName}})(n.ptr).Clone()
		r := New{{.ShortName}}{{$sfx}}(c)
		return &r
{{- end}}
	}
	return &{{.Name}}{}
}
{{- end}}{{end}}
`))

func findCloneableInterfaces(f *ast.File) []CloneableInterface {
	var interfaces []CloneableInterface
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			switch typeSpec.Name.Name {
			case "Node", "VisitableNode", "CloneableNode":
				continue
			}

			switch t := typeSpec.Type.(type) {
			case *ast.InterfaceType:
				idx := slices.IndexFunc(t.Methods.List, func(a *ast.Field) bool {
					if len(a.Names) == 0 {
						return false
					}
					return strings.HasPrefix(a.Names[0].Name, "_")
				})
				if idx == -1 {
					continue
				}
				interfaces = append(interfaces, CloneableInterface{
					Name:       typeSpec.Name.Name,
					UniqueFunc: t.Methods.List[idx].Names[0].Name,
				})
			}
		}
	}
	return interfaces
}

func findStructsForInterfaces(f *ast.File, interfaces []CloneableInterface) {
	for _, decl := range f.Decls {
		funcDecl, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}
		if funcDecl.Recv == nil || len(funcDecl.Recv.List) == 0 {
			continue
		}
		starExpr, ok := funcDecl.Recv.List[0].Type.(*ast.StarExpr)
		if !ok {
			continue
		}
		ident, ok := starExpr.X.(*ast.Ident)
		if !ok {
			continue
		}
		idx := slices.IndexFunc(interfaces, func(a CloneableInterface) bool {
			return a.UniqueFunc == funcDecl.Name.Name
		})
		if idx == -1 {
			continue
		}
		interfaces[idx].Structs = append(interfaces[idx].Structs, ident.Name)
	}
}

func findCloneableNodes(f *ast.File, specs map[string]astgen.UnionSpec) (types []CloneableNodeType) {
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			switch typeSpec.Name.Name {
			case "ScopeContext", "Id":
				continue
			}

			switch t := typeSpec.Type.(type) {
			case *ast.StructType:
				// Spec structs (//union: ...) enumerate a union's variants for
				// codegen; they are not real nodes.
				if astgen.UnionWrapper(typeSpec.Doc) != "" {
					continue
				}
				node := CloneableNodeType{
					Type:     NodeTypeStruct,
					Name:     typeSpec.Name.Name,
					Children: findStructChildren(t.Fields.List),
				}
				if union, ok := specs[typeSpec.Name.Name]; ok {
					node.IsUnion = true
					node.Variants = union.Variants
					node.KindPrefix = union.KindPrefix
					node.ConstructorSfx = union.ConstructorSfx
				}
				types = append(types, node)
			case *ast.ArrayType:
				types = append(types, CloneableNodeType{
					Type: NodeTypeSlice,
					Name: typeSpec.Name.Name,
				})
			}
		}
	}
	return types
}

func findStructChildren(fields []*ast.Field) (children []Child) {
	for _, field := range fields {
		optional := field.Tag != nil && field.Tag.Value == "`optional:\"true\"`"

		switch fieldType := field.Type.(type) {
		case *ast.SelectorExpr:
			children = appendNamedChildren(children, field.Names, "", false, false, optional)
		case *ast.Ident:
			if len(field.Names) == 0 {
				children = append(children, newChild(fieldType.Name, fieldType.Name, true, false, optional))
				continue
			}

			switch fieldType.Name {
			case "Idx", "any", "bool", "int", "ScopeContext", "string", "MethodKind", "Token", "VarKind",
				"float64", "UnaryOperator", "AssignmentOperator", "BinaryOperator", "UpdateOperator", "LogicalOperator",
				"MetaPropertyKind":
				children = appendNamedChildren(children, field.Names, fieldType.Name, false, false, optional)
			default:
				children = appendNamedChildren(children, field.Names, fieldType.Name, true, false, optional)
			}
		case *ast.StarExpr:
			if ident, ok := fieldType.X.(*ast.Ident); ok {
				if ident.Name == "string" {
					children = appendNamedChildren(children, field.Names, ident.Name, false, false, optional)
					continue
				}
				children = appendNamedChildren(children, field.Names, ident.Name, true, true, optional)
			} else {
				// Pointer to a type from another package (e.g. *big.Int).
				// Shallow-copy the pointer — not a cloneable AST node.
				children = appendNamedChildren(children, field.Names, "", false, false, optional)
			}
		}
	}
	return children
}

func appendNamedChildren(children []Child, names []*ast.Ident, fieldType string, cloneable, pointer, optional bool) []Child {
	for _, name := range names {
		children = append(children, newChild(name.Name, fieldType, cloneable, pointer, optional))
	}
	return children
}
