//go:build ignore

package main

import (
	"bytes"
	"cmp"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"log"
	"os"
	"slices"
	"text/template"

	"github.com/t14raptor/go-fast/ast/internal/astgen"
)

func main() {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, "./ast", func(info fs.FileInfo) bool {
		name := info.Name()
		return name != "union.go" && name != "visit.go" && name != "clone.go"
	}, parser.ParseComments)
	if err != nil {
		log.Fatal(err)
	}

	unions := findUnions(pkgs["ast"])

	var buf bytes.Buffer
	if err := unionTemplate.Execute(&buf, unions); err != nil {
		log.Fatalf("template error: %v", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		os.WriteFile("ast/union.go", buf.Bytes(), 0644)
		log.Fatalf("format error: %v", err)
	}

	if err := os.WriteFile("ast/union.go", formatted, 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("Generated ast/union.go")
}

var unionTemplate = template.Must(template.New("union").Parse(`// Code generated by gen_union.go; DO NOT EDIT.

package ast

import "unsafe"

{{range $u := . -}}
// ---- {{$u.WrapperType}} tagged union ----

type {{$u.KindType}} uint8

const (
	{{$u.KindPrefix}}None {{$u.KindType}} = iota
{{- range $u.Variants}}
	{{$u.KindPrefix}}{{.ShortName}}
{{- end}}
)

func (k {{$u.KindType}}) String() string {
	switch k {
	case {{$u.KindPrefix}}None:
		return "{{$u.KindPrefix}}None"
{{- range $u.Variants}}
	case {{$u.KindPrefix}}{{.ShortName}}:
		return "{{$u.KindPrefix}}{{.ShortName}}"
{{- end}}
	}
	return "{{$u.KindType}}(?)"
}

func (n *{{$u.WrapperType}}) Kind() {{$u.KindType}} { return n.kind }
func (n *{{$u.WrapperType}}) IsNone() bool { return n.kind == {{$u.KindPrefix}}None }

{{range $u.Variants -}}
func New{{.ShortName}}{{$u.ConstructorSfx}}(n *{{.TypeName}}) {{$u.WrapperType}} {
	return {{$u.WrapperType}}{kind: {{$u.KindPrefix}}{{.ShortName}}, ptr: unsafe.Pointer(n)}
}

func (n *{{$u.WrapperType}}) {{.ShortName}}() (*{{.TypeName}}, bool) {
	if n.kind == {{$u.KindPrefix}}{{.ShortName}} {
		return (*{{.TypeName}})(n.ptr), true
	}
	return nil, false
}

func (n *{{$u.WrapperType}}) Must{{.ShortName}}() *{{.TypeName}} {
	if n.kind != {{$u.KindPrefix}}{{.ShortName}} {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*{{.TypeName}})(n.ptr)
}

func (n *{{$u.WrapperType}}) Is{{.ShortName}}() bool {
	return n.kind == {{$u.KindPrefix}}{{.ShortName}}
}

{{end -}}
func (n *{{$u.WrapperType}}) Idx0() Idx {
	switch n.kind {
{{- range $u.Variants}}
	case {{$u.KindPrefix}}{{.ShortName}}:
		return (*{{.TypeName}})(n.ptr).Idx0()
{{- end}}
	}
	return 0
}

func (n *{{$u.WrapperType}}) Idx1() Idx {
	switch n.kind {
{{- range $u.Variants}}
	case {{$u.KindPrefix}}{{.ShortName}}:
		return (*{{.TypeName}})(n.ptr).Idx1()
{{- end}}
	}
	return 0
}

func (n *{{$u.WrapperType}}) Unwrap() VisitableNode {
	if n == nil { return nil }
	switch n.kind {
{{- range $u.Variants}}
	case {{$u.KindPrefix}}{{.ShortName}}:
		return (*{{.TypeName}})(n.ptr)
{{- end}}
	}
	return nil
}

{{end -}}
`))

// findUnions returns every tagged union in the package, sorted by wrapper type
// so the generated output is stable (FindUnionSpecs returns a map).
func findUnions(pkg *ast.Package) []astgen.UnionSpec {
	unions := make([]astgen.UnionSpec, 0)
	for _, spec := range astgen.FindUnionSpecs(pkg.Files) {
		unions = append(unions, spec)
	}
	slices.SortFunc(unions, func(a, b astgen.UnionSpec) int {
		return cmp.Compare(a.WrapperType, b.WrapperType)
	})
	return unions
}
