// Code generated by gen_union.go; DO NOT EDIT.

package ast

import "unsafe"

// ---- ClassElement tagged union ----

type ClassElemKind uint8

const (
	ClassElemNone ClassElemKind = iota
	ClassElemFieldDef
	ClassElemMethodDef
	ClassElemStaticBlock
)

func (k ClassElemKind) String() string {
	switch k {
	case ClassElemNone:
		return "ClassElemNone"
	case ClassElemFieldDef:
		return "ClassElemFieldDef"
	case ClassElemMethodDef:
		return "ClassElemMethodDef"
	case ClassElemStaticBlock:
		return "ClassElemStaticBlock"
	}
	return "ClassElemKind(?)"
}

func (n *ClassElement) Kind() ClassElemKind { return n.kind }
func (n *ClassElement) IsNone() bool        { return n.kind == ClassElemNone }

func NewFieldDefClassElem(n *FieldDefinition) ClassElement {
	return ClassElement{kind: ClassElemFieldDef, ptr: unsafe.Pointer(n)}
}

func (n *ClassElement) FieldDef() (*FieldDefinition, bool) {
	if n.kind == ClassElemFieldDef {
		return (*FieldDefinition)(n.ptr), true
	}
	return nil, false
}

func (n *ClassElement) MustFieldDef() *FieldDefinition {
	if n.kind != ClassElemFieldDef {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*FieldDefinition)(n.ptr)
}

func (n *ClassElement) IsFieldDef() bool {
	return n.kind == ClassElemFieldDef
}

func NewMethodDefClassElem(n *MethodDefinition) ClassElement {
	return ClassElement{kind: ClassElemMethodDef, ptr: unsafe.Pointer(n)}
}

func (n *ClassElement) MethodDef() (*MethodDefinition, bool) {
	if n.kind == ClassElemMethodDef {
		return (*MethodDefinition)(n.ptr), true
	}
	return nil, false
}

func (n *ClassElement) MustMethodDef() *MethodDefinition {
	if n.kind != ClassElemMethodDef {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*MethodDefinition)(n.ptr)
}

func (n *ClassElement) IsMethodDef() bool {
	return n.kind == ClassElemMethodDef
}

func NewStaticBlockClassElem(n *ClassStaticBlock) ClassElement {
	return ClassElement{kind: ClassElemStaticBlock, ptr: unsafe.Pointer(n)}
}

func (n *ClassElement) StaticBlock() (*ClassStaticBlock, bool) {
	if n.kind == ClassElemStaticBlock {
		return (*ClassStaticBlock)(n.ptr), true
	}
	return nil, false
}

func (n *ClassElement) MustStaticBlock() *ClassStaticBlock {
	if n.kind != ClassElemStaticBlock {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ClassStaticBlock)(n.ptr)
}

func (n *ClassElement) IsStaticBlock() bool {
	return n.kind == ClassElemStaticBlock
}

func (n *ClassElement) Idx0() Idx {
	switch n.kind {
	case ClassElemFieldDef:
		return (*FieldDefinition)(n.ptr).Idx0()
	case ClassElemMethodDef:
		return (*MethodDefinition)(n.ptr).Idx0()
	case ClassElemStaticBlock:
		return (*ClassStaticBlock)(n.ptr).Idx0()
	}
	return 0
}

func (n *ClassElement) Idx1() Idx {
	switch n.kind {
	case ClassElemFieldDef:
		return (*FieldDefinition)(n.ptr).Idx1()
	case ClassElemMethodDef:
		return (*MethodDefinition)(n.ptr).Idx1()
	case ClassElemStaticBlock:
		return (*ClassStaticBlock)(n.ptr).Idx1()
	}
	return 0
}

func (n *ClassElement) Unwrap() VisitableNode {
	if n == nil {
		return nil
	}
	switch n.kind {
	case ClassElemFieldDef:
		return (*FieldDefinition)(n.ptr)
	case ClassElemMethodDef:
		return (*MethodDefinition)(n.ptr)
	case ClassElemStaticBlock:
		return (*ClassStaticBlock)(n.ptr)
	}
	return nil
}

// ---- ConciseBody tagged union ----

type ConciseBodyKind uint8

const (
	ConciseBodyNone ConciseBodyKind = iota
	ConciseBodyBlock
	ConciseBodyExpr
)

func (k ConciseBodyKind) String() string {
	switch k {
	case ConciseBodyNone:
		return "ConciseBodyNone"
	case ConciseBodyBlock:
		return "ConciseBodyBlock"
	case ConciseBodyExpr:
		return "ConciseBodyExpr"
	}
	return "ConciseBodyKind(?)"
}

func (n *ConciseBody) Kind() ConciseBodyKind { return n.kind }
func (n *ConciseBody) IsNone() bool          { return n.kind == ConciseBodyNone }

func NewBlockConciseBody(n *BlockStatement) ConciseBody {
	return ConciseBody{kind: ConciseBodyBlock, ptr: unsafe.Pointer(n)}
}

func (n *ConciseBody) Block() (*BlockStatement, bool) {
	if n.kind == ConciseBodyBlock {
		return (*BlockStatement)(n.ptr), true
	}
	return nil, false
}

func (n *ConciseBody) MustBlock() *BlockStatement {
	if n.kind != ConciseBodyBlock {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*BlockStatement)(n.ptr)
}

func (n *ConciseBody) IsBlock() bool {
	return n.kind == ConciseBodyBlock
}

func NewExprConciseBody(n *Expression) ConciseBody {
	return ConciseBody{kind: ConciseBodyExpr, ptr: unsafe.Pointer(n)}
}

func (n *ConciseBody) Expr() (*Expression, bool) {
	if n.kind == ConciseBodyExpr {
		return (*Expression)(n.ptr), true
	}
	return nil, false
}

func (n *ConciseBody) MustExpr() *Expression {
	if n.kind != ConciseBodyExpr {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*Expression)(n.ptr)
}

func (n *ConciseBody) IsExpr() bool {
	return n.kind == ConciseBodyExpr
}

func (n *ConciseBody) Idx0() Idx {
	switch n.kind {
	case ConciseBodyBlock:
		return (*BlockStatement)(n.ptr).Idx0()
	case ConciseBodyExpr:
		return (*Expression)(n.ptr).Idx0()
	}
	return 0
}

func (n *ConciseBody) Idx1() Idx {
	switch n.kind {
	case ConciseBodyBlock:
		return (*BlockStatement)(n.ptr).Idx1()
	case ConciseBodyExpr:
		return (*Expression)(n.ptr).Idx1()
	}
	return 0
}

func (n *ConciseBody) Unwrap() VisitableNode {
	if n == nil {
		return nil
	}
	switch n.kind {
	case ConciseBodyBlock:
		return (*BlockStatement)(n.ptr)
	case ConciseBodyExpr:
		return (*Expression)(n.ptr)
	}
	return nil
}

// ---- Expression tagged union ----

type ExprKind uint8

const (
	ExprNone ExprKind = iota
	ExprArrayLit
	ExprArrowFuncLit
	ExprAssign
	ExprAwait
	ExprBigIntLit
	ExprBinary
	ExprBoolLit
	ExprCall
	ExprClassLit
	ExprConditional
	ExprFuncLit
	ExprIdentifier
	ExprInvalid
	ExprLogical
	ExprMember
	ExprMetaProp
	ExprNew
	ExprNullLit
	ExprNumberLit
	ExprObjectLit
	ExprOptional
	ExprOptionalChain
	ExprPrivDot
	ExprPrivIdentifier
	ExprRegExpLit
	ExprSequence
	ExprSpread
	ExprStringLit
	ExprSuper
	ExprThis
	ExprTmplLit
	ExprUnary
	ExprUpdate
	ExprVarDeclarator
	ExprYield
)

func (k ExprKind) String() string {
	switch k {
	case ExprNone:
		return "ExprNone"
	case ExprArrayLit:
		return "ExprArrayLit"
	case ExprArrowFuncLit:
		return "ExprArrowFuncLit"
	case ExprAssign:
		return "ExprAssign"
	case ExprAwait:
		return "ExprAwait"
	case ExprBigIntLit:
		return "ExprBigIntLit"
	case ExprBinary:
		return "ExprBinary"
	case ExprBoolLit:
		return "ExprBoolLit"
	case ExprCall:
		return "ExprCall"
	case ExprClassLit:
		return "ExprClassLit"
	case ExprConditional:
		return "ExprConditional"
	case ExprFuncLit:
		return "ExprFuncLit"
	case ExprIdentifier:
		return "ExprIdentifier"
	case ExprInvalid:
		return "ExprInvalid"
	case ExprLogical:
		return "ExprLogical"
	case ExprMember:
		return "ExprMember"
	case ExprMetaProp:
		return "ExprMetaProp"
	case ExprNew:
		return "ExprNew"
	case ExprNullLit:
		return "ExprNullLit"
	case ExprNumberLit:
		return "ExprNumberLit"
	case ExprObjectLit:
		return "ExprObjectLit"
	case ExprOptional:
		return "ExprOptional"
	case ExprOptionalChain:
		return "ExprOptionalChain"
	case ExprPrivDot:
		return "ExprPrivDot"
	case ExprPrivIdentifier:
		return "ExprPrivIdentifier"
	case ExprRegExpLit:
		return "ExprRegExpLit"
	case ExprSequence:
		return "ExprSequence"
	case ExprSpread:
		return "ExprSpread"
	case ExprStringLit:
		return "ExprStringLit"
	case ExprSuper:
		return "ExprSuper"
	case ExprThis:
		return "ExprThis"
	case ExprTmplLit:
		return "ExprTmplLit"
	case ExprUnary:
		return "ExprUnary"
	case ExprUpdate:
		return "ExprUpdate"
	case ExprVarDeclarator:
		return "ExprVarDeclarator"
	case ExprYield:
		return "ExprYield"
	}
	return "ExprKind(?)"
}

func (n *Expression) Kind() ExprKind { return n.kind }
func (n *Expression) IsNone() bool   { return n.kind == ExprNone }

func NewArrayLitExpr(n *ArrayLiteral) Expression {
	return Expression{kind: ExprArrayLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) ArrayLit() (*ArrayLiteral, bool) {
	if n.kind == ExprArrayLit {
		return (*ArrayLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustArrayLit() *ArrayLiteral {
	if n.kind != ExprArrayLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ArrayLiteral)(n.ptr)
}

func (n *Expression) IsArrayLit() bool {
	return n.kind == ExprArrayLit
}

func NewArrowFuncLitExpr(n *ArrowFunctionLiteral) Expression {
	return Expression{kind: ExprArrowFuncLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) ArrowFuncLit() (*ArrowFunctionLiteral, bool) {
	if n.kind == ExprArrowFuncLit {
		return (*ArrowFunctionLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustArrowFuncLit() *ArrowFunctionLiteral {
	if n.kind != ExprArrowFuncLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ArrowFunctionLiteral)(n.ptr)
}

func (n *Expression) IsArrowFuncLit() bool {
	return n.kind == ExprArrowFuncLit
}

func NewAssignExpr(n *AssignExpression) Expression {
	return Expression{kind: ExprAssign, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Assign() (*AssignExpression, bool) {
	if n.kind == ExprAssign {
		return (*AssignExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustAssign() *AssignExpression {
	if n.kind != ExprAssign {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*AssignExpression)(n.ptr)
}

func (n *Expression) IsAssign() bool {
	return n.kind == ExprAssign
}

func NewAwaitExpr(n *AwaitExpression) Expression {
	return Expression{kind: ExprAwait, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Await() (*AwaitExpression, bool) {
	if n.kind == ExprAwait {
		return (*AwaitExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustAwait() *AwaitExpression {
	if n.kind != ExprAwait {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*AwaitExpression)(n.ptr)
}

func (n *Expression) IsAwait() bool {
	return n.kind == ExprAwait
}

func NewBigIntLitExpr(n *BigIntLiteral) Expression {
	return Expression{kind: ExprBigIntLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) BigIntLit() (*BigIntLiteral, bool) {
	if n.kind == ExprBigIntLit {
		return (*BigIntLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustBigIntLit() *BigIntLiteral {
	if n.kind != ExprBigIntLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*BigIntLiteral)(n.ptr)
}

func (n *Expression) IsBigIntLit() bool {
	return n.kind == ExprBigIntLit
}

func NewBinaryExpr(n *BinaryExpression) Expression {
	return Expression{kind: ExprBinary, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Binary() (*BinaryExpression, bool) {
	if n.kind == ExprBinary {
		return (*BinaryExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustBinary() *BinaryExpression {
	if n.kind != ExprBinary {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*BinaryExpression)(n.ptr)
}

func (n *Expression) IsBinary() bool {
	return n.kind == ExprBinary
}

func NewBoolLitExpr(n *BooleanLiteral) Expression {
	return Expression{kind: ExprBoolLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) BoolLit() (*BooleanLiteral, bool) {
	if n.kind == ExprBoolLit {
		return (*BooleanLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustBoolLit() *BooleanLiteral {
	if n.kind != ExprBoolLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*BooleanLiteral)(n.ptr)
}

func (n *Expression) IsBoolLit() bool {
	return n.kind == ExprBoolLit
}

func NewCallExpr(n *CallExpression) Expression {
	return Expression{kind: ExprCall, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Call() (*CallExpression, bool) {
	if n.kind == ExprCall {
		return (*CallExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustCall() *CallExpression {
	if n.kind != ExprCall {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*CallExpression)(n.ptr)
}

func (n *Expression) IsCall() bool {
	return n.kind == ExprCall
}

func NewClassLitExpr(n *ClassLiteral) Expression {
	return Expression{kind: ExprClassLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) ClassLit() (*ClassLiteral, bool) {
	if n.kind == ExprClassLit {
		return (*ClassLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustClassLit() *ClassLiteral {
	if n.kind != ExprClassLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ClassLiteral)(n.ptr)
}

func (n *Expression) IsClassLit() bool {
	return n.kind == ExprClassLit
}

func NewConditionalExpr(n *ConditionalExpression) Expression {
	return Expression{kind: ExprConditional, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Conditional() (*ConditionalExpression, bool) {
	if n.kind == ExprConditional {
		return (*ConditionalExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustConditional() *ConditionalExpression {
	if n.kind != ExprConditional {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ConditionalExpression)(n.ptr)
}

func (n *Expression) IsConditional() bool {
	return n.kind == ExprConditional
}

func NewFuncLitExpr(n *FunctionLiteral) Expression {
	return Expression{kind: ExprFuncLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) FuncLit() (*FunctionLiteral, bool) {
	if n.kind == ExprFuncLit {
		return (*FunctionLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustFuncLit() *FunctionLiteral {
	if n.kind != ExprFuncLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*FunctionLiteral)(n.ptr)
}

func (n *Expression) IsFuncLit() bool {
	return n.kind == ExprFuncLit
}

func NewIdentifierExpr(n *Identifier) Expression {
	return Expression{kind: ExprIdentifier, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Identifier() (*Identifier, bool) {
	if n.kind == ExprIdentifier {
		return (*Identifier)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustIdentifier() *Identifier {
	if n.kind != ExprIdentifier {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*Identifier)(n.ptr)
}

func (n *Expression) IsIdentifier() bool {
	return n.kind == ExprIdentifier
}

func NewInvalidExpr(n *InvalidExpression) Expression {
	return Expression{kind: ExprInvalid, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Invalid() (*InvalidExpression, bool) {
	if n.kind == ExprInvalid {
		return (*InvalidExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustInvalid() *InvalidExpression {
	if n.kind != ExprInvalid {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*InvalidExpression)(n.ptr)
}

func (n *Expression) IsInvalid() bool {
	return n.kind == ExprInvalid
}

func NewLogicalExpr(n *LogicalExpression) Expression {
	return Expression{kind: ExprLogical, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Logical() (*LogicalExpression, bool) {
	if n.kind == ExprLogical {
		return (*LogicalExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustLogical() *LogicalExpression {
	if n.kind != ExprLogical {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*LogicalExpression)(n.ptr)
}

func (n *Expression) IsLogical() bool {
	return n.kind == ExprLogical
}

func NewMemberExpr(n *MemberExpression) Expression {
	return Expression{kind: ExprMember, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Member() (*MemberExpression, bool) {
	if n.kind == ExprMember {
		return (*MemberExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustMember() *MemberExpression {
	if n.kind != ExprMember {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*MemberExpression)(n.ptr)
}

func (n *Expression) IsMember() bool {
	return n.kind == ExprMember
}

func NewMetaPropExpr(n *MetaProperty) Expression {
	return Expression{kind: ExprMetaProp, ptr: unsafe.Pointer(n)}
}

func (n *Expression) MetaProp() (*MetaProperty, bool) {
	if n.kind == ExprMetaProp {
		return (*MetaProperty)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustMetaProp() *MetaProperty {
	if n.kind != ExprMetaProp {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*MetaProperty)(n.ptr)
}

func (n *Expression) IsMetaProp() bool {
	return n.kind == ExprMetaProp
}

func NewNewExpr(n *NewExpression) Expression {
	return Expression{kind: ExprNew, ptr: unsafe.Pointer(n)}
}

func (n *Expression) New() (*NewExpression, bool) {
	if n.kind == ExprNew {
		return (*NewExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustNew() *NewExpression {
	if n.kind != ExprNew {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*NewExpression)(n.ptr)
}

func (n *Expression) IsNew() bool {
	return n.kind == ExprNew
}

func NewNullLitExpr(n *NullLiteral) Expression {
	return Expression{kind: ExprNullLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) NullLit() (*NullLiteral, bool) {
	if n.kind == ExprNullLit {
		return (*NullLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustNullLit() *NullLiteral {
	if n.kind != ExprNullLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*NullLiteral)(n.ptr)
}

func (n *Expression) IsNullLit() bool {
	return n.kind == ExprNullLit
}

func NewNumberLitExpr(n *NumberLiteral) Expression {
	return Expression{kind: ExprNumberLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) NumberLit() (*NumberLiteral, bool) {
	if n.kind == ExprNumberLit {
		return (*NumberLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustNumberLit() *NumberLiteral {
	if n.kind != ExprNumberLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*NumberLiteral)(n.ptr)
}

func (n *Expression) IsNumberLit() bool {
	return n.kind == ExprNumberLit
}

func NewObjectLitExpr(n *ObjectLiteral) Expression {
	return Expression{kind: ExprObjectLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) ObjectLit() (*ObjectLiteral, bool) {
	if n.kind == ExprObjectLit {
		return (*ObjectLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustObjectLit() *ObjectLiteral {
	if n.kind != ExprObjectLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ObjectLiteral)(n.ptr)
}

func (n *Expression) IsObjectLit() bool {
	return n.kind == ExprObjectLit
}

func NewOptionalExpr(n *Optional) Expression {
	return Expression{kind: ExprOptional, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Optional() (*Optional, bool) {
	if n.kind == ExprOptional {
		return (*Optional)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustOptional() *Optional {
	if n.kind != ExprOptional {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*Optional)(n.ptr)
}

func (n *Expression) IsOptional() bool {
	return n.kind == ExprOptional
}

func NewOptionalChainExpr(n *OptionalChain) Expression {
	return Expression{kind: ExprOptionalChain, ptr: unsafe.Pointer(n)}
}

func (n *Expression) OptionalChain() (*OptionalChain, bool) {
	if n.kind == ExprOptionalChain {
		return (*OptionalChain)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustOptionalChain() *OptionalChain {
	if n.kind != ExprOptionalChain {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*OptionalChain)(n.ptr)
}

func (n *Expression) IsOptionalChain() bool {
	return n.kind == ExprOptionalChain
}

func NewPrivDotExpr(n *PrivateDotExpression) Expression {
	return Expression{kind: ExprPrivDot, ptr: unsafe.Pointer(n)}
}

func (n *Expression) PrivDot() (*PrivateDotExpression, bool) {
	if n.kind == ExprPrivDot {
		return (*PrivateDotExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustPrivDot() *PrivateDotExpression {
	if n.kind != ExprPrivDot {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*PrivateDotExpression)(n.ptr)
}

func (n *Expression) IsPrivDot() bool {
	return n.kind == ExprPrivDot
}

func NewPrivIdentifierExpr(n *PrivateIdentifier) Expression {
	return Expression{kind: ExprPrivIdentifier, ptr: unsafe.Pointer(n)}
}

func (n *Expression) PrivIdentifier() (*PrivateIdentifier, bool) {
	if n.kind == ExprPrivIdentifier {
		return (*PrivateIdentifier)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustPrivIdentifier() *PrivateIdentifier {
	if n.kind != ExprPrivIdentifier {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*PrivateIdentifier)(n.ptr)
}

func (n *Expression) IsPrivIdentifier() bool {
	return n.kind == ExprPrivIdentifier
}

func NewRegExpLitExpr(n *RegExpLiteral) Expression {
	return Expression{kind: ExprRegExpLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) RegExpLit() (*RegExpLiteral, bool) {
	if n.kind == ExprRegExpLit {
		return (*RegExpLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustRegExpLit() *RegExpLiteral {
	if n.kind != ExprRegExpLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*RegExpLiteral)(n.ptr)
}

func (n *Expression) IsRegExpLit() bool {
	return n.kind == ExprRegExpLit
}

func NewSequenceExpr(n *SequenceExpression) Expression {
	return Expression{kind: ExprSequence, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Sequence() (*SequenceExpression, bool) {
	if n.kind == ExprSequence {
		return (*SequenceExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustSequence() *SequenceExpression {
	if n.kind != ExprSequence {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*SequenceExpression)(n.ptr)
}

func (n *Expression) IsSequence() bool {
	return n.kind == ExprSequence
}

func NewSpreadExpr(n *SpreadElement) Expression {
	return Expression{kind: ExprSpread, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Spread() (*SpreadElement, bool) {
	if n.kind == ExprSpread {
		return (*SpreadElement)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustSpread() *SpreadElement {
	if n.kind != ExprSpread {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*SpreadElement)(n.ptr)
}

func (n *Expression) IsSpread() bool {
	return n.kind == ExprSpread
}

func NewStringLitExpr(n *StringLiteral) Expression {
	return Expression{kind: ExprStringLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) StringLit() (*StringLiteral, bool) {
	if n.kind == ExprStringLit {
		return (*StringLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustStringLit() *StringLiteral {
	if n.kind != ExprStringLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*StringLiteral)(n.ptr)
}

func (n *Expression) IsStringLit() bool {
	return n.kind == ExprStringLit
}

func NewSuperExpr(n *SuperExpression) Expression {
	return Expression{kind: ExprSuper, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Super() (*SuperExpression, bool) {
	if n.kind == ExprSuper {
		return (*SuperExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustSuper() *SuperExpression {
	if n.kind != ExprSuper {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*SuperExpression)(n.ptr)
}

func (n *Expression) IsSuper() bool {
	return n.kind == ExprSuper
}

func NewThisExpr(n *ThisExpression) Expression {
	return Expression{kind: ExprThis, ptr: unsafe.Pointer(n)}
}

func (n *Expression) This() (*ThisExpression, bool) {
	if n.kind == ExprThis {
		return (*ThisExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustThis() *ThisExpression {
	if n.kind != ExprThis {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ThisExpression)(n.ptr)
}

func (n *Expression) IsThis() bool {
	return n.kind == ExprThis
}

func NewTmplLitExpr(n *TemplateLiteral) Expression {
	return Expression{kind: ExprTmplLit, ptr: unsafe.Pointer(n)}
}

func (n *Expression) TmplLit() (*TemplateLiteral, bool) {
	if n.kind == ExprTmplLit {
		return (*TemplateLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustTmplLit() *TemplateLiteral {
	if n.kind != ExprTmplLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*TemplateLiteral)(n.ptr)
}

func (n *Expression) IsTmplLit() bool {
	return n.kind == ExprTmplLit
}

func NewUnaryExpr(n *UnaryExpression) Expression {
	return Expression{kind: ExprUnary, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Unary() (*UnaryExpression, bool) {
	if n.kind == ExprUnary {
		return (*UnaryExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustUnary() *UnaryExpression {
	if n.kind != ExprUnary {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*UnaryExpression)(n.ptr)
}

func (n *Expression) IsUnary() bool {
	return n.kind == ExprUnary
}

func NewUpdateExpr(n *UpdateExpression) Expression {
	return Expression{kind: ExprUpdate, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Update() (*UpdateExpression, bool) {
	if n.kind == ExprUpdate {
		return (*UpdateExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustUpdate() *UpdateExpression {
	if n.kind != ExprUpdate {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*UpdateExpression)(n.ptr)
}

func (n *Expression) IsUpdate() bool {
	return n.kind == ExprUpdate
}

func NewVarDeclaratorExpr(n *VariableDeclarator) Expression {
	return Expression{kind: ExprVarDeclarator, ptr: unsafe.Pointer(n)}
}

func (n *Expression) VarDeclarator() (*VariableDeclarator, bool) {
	if n.kind == ExprVarDeclarator {
		return (*VariableDeclarator)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustVarDeclarator() *VariableDeclarator {
	if n.kind != ExprVarDeclarator {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*VariableDeclarator)(n.ptr)
}

func (n *Expression) IsVarDeclarator() bool {
	return n.kind == ExprVarDeclarator
}

func NewYieldExpr(n *YieldExpression) Expression {
	return Expression{kind: ExprYield, ptr: unsafe.Pointer(n)}
}

func (n *Expression) Yield() (*YieldExpression, bool) {
	if n.kind == ExprYield {
		return (*YieldExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Expression) MustYield() *YieldExpression {
	if n.kind != ExprYield {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*YieldExpression)(n.ptr)
}

func (n *Expression) IsYield() bool {
	return n.kind == ExprYield
}

func (n *Expression) Idx0() Idx {
	switch n.kind {
	case ExprArrayLit:
		return (*ArrayLiteral)(n.ptr).Idx0()
	case ExprArrowFuncLit:
		return (*ArrowFunctionLiteral)(n.ptr).Idx0()
	case ExprAssign:
		return (*AssignExpression)(n.ptr).Idx0()
	case ExprAwait:
		return (*AwaitExpression)(n.ptr).Idx0()
	case ExprBigIntLit:
		return (*BigIntLiteral)(n.ptr).Idx0()
	case ExprBinary:
		return (*BinaryExpression)(n.ptr).Idx0()
	case ExprBoolLit:
		return (*BooleanLiteral)(n.ptr).Idx0()
	case ExprCall:
		return (*CallExpression)(n.ptr).Idx0()
	case ExprClassLit:
		return (*ClassLiteral)(n.ptr).Idx0()
	case ExprConditional:
		return (*ConditionalExpression)(n.ptr).Idx0()
	case ExprFuncLit:
		return (*FunctionLiteral)(n.ptr).Idx0()
	case ExprIdentifier:
		return (*Identifier)(n.ptr).Idx0()
	case ExprInvalid:
		return (*InvalidExpression)(n.ptr).Idx0()
	case ExprLogical:
		return (*LogicalExpression)(n.ptr).Idx0()
	case ExprMember:
		return (*MemberExpression)(n.ptr).Idx0()
	case ExprMetaProp:
		return (*MetaProperty)(n.ptr).Idx0()
	case ExprNew:
		return (*NewExpression)(n.ptr).Idx0()
	case ExprNullLit:
		return (*NullLiteral)(n.ptr).Idx0()
	case ExprNumberLit:
		return (*NumberLiteral)(n.ptr).Idx0()
	case ExprObjectLit:
		return (*ObjectLiteral)(n.ptr).Idx0()
	case ExprOptional:
		return (*Optional)(n.ptr).Idx0()
	case ExprOptionalChain:
		return (*OptionalChain)(n.ptr).Idx0()
	case ExprPrivDot:
		return (*PrivateDotExpression)(n.ptr).Idx0()
	case ExprPrivIdentifier:
		return (*PrivateIdentifier)(n.ptr).Idx0()
	case ExprRegExpLit:
		return (*RegExpLiteral)(n.ptr).Idx0()
	case ExprSequence:
		return (*SequenceExpression)(n.ptr).Idx0()
	case ExprSpread:
		return (*SpreadElement)(n.ptr).Idx0()
	case ExprStringLit:
		return (*StringLiteral)(n.ptr).Idx0()
	case ExprSuper:
		return (*SuperExpression)(n.ptr).Idx0()
	case ExprThis:
		return (*ThisExpression)(n.ptr).Idx0()
	case ExprTmplLit:
		return (*TemplateLiteral)(n.ptr).Idx0()
	case ExprUnary:
		return (*UnaryExpression)(n.ptr).Idx0()
	case ExprUpdate:
		return (*UpdateExpression)(n.ptr).Idx0()
	case ExprVarDeclarator:
		return (*VariableDeclarator)(n.ptr).Idx0()
	case ExprYield:
		return (*YieldExpression)(n.ptr).Idx0()
	}
	return 0
}

func (n *Expression) Idx1() Idx {
	switch n.kind {
	case ExprArrayLit:
		return (*ArrayLiteral)(n.ptr).Idx1()
	case ExprArrowFuncLit:
		return (*ArrowFunctionLiteral)(n.ptr).Idx1()
	case ExprAssign:
		return (*AssignExpression)(n.ptr).Idx1()
	case ExprAwait:
		return (*AwaitExpression)(n.ptr).Idx1()
	case ExprBigIntLit:
		return (*BigIntLiteral)(n.ptr).Idx1()
	case ExprBinary:
		return (*BinaryExpression)(n.ptr).Idx1()
	case ExprBoolLit:
		return (*BooleanLiteral)(n.ptr).Idx1()
	case ExprCall:
		return (*CallExpression)(n.ptr).Idx1()
	case ExprClassLit:
		return (*ClassLiteral)(n.ptr).Idx1()
	case ExprConditional:
		return (*ConditionalExpression)(n.ptr).Idx1()
	case ExprFuncLit:
		return (*FunctionLiteral)(n.ptr).Idx1()
	case ExprIdentifier:
		return (*Identifier)(n.ptr).Idx1()
	case ExprInvalid:
		return (*InvalidExpression)(n.ptr).Idx1()
	case ExprLogical:
		return (*LogicalExpression)(n.ptr).Idx1()
	case ExprMember:
		return (*MemberExpression)(n.ptr).Idx1()
	case ExprMetaProp:
		return (*MetaProperty)(n.ptr).Idx1()
	case ExprNew:
		return (*NewExpression)(n.ptr).Idx1()
	case ExprNullLit:
		return (*NullLiteral)(n.ptr).Idx1()
	case ExprNumberLit:
		return (*NumberLiteral)(n.ptr).Idx1()
	case ExprObjectLit:
		return (*ObjectLiteral)(n.ptr).Idx1()
	case ExprOptional:
		return (*Optional)(n.ptr).Idx1()
	case ExprOptionalChain:
		return (*OptionalChain)(n.ptr).Idx1()
	case ExprPrivDot:
		return (*PrivateDotExpression)(n.ptr).Idx1()
	case ExprPrivIdentifier:
		return (*PrivateIdentifier)(n.ptr).Idx1()
	case ExprRegExpLit:
		return (*RegExpLiteral)(n.ptr).Idx1()
	case ExprSequence:
		return (*SequenceExpression)(n.ptr).Idx1()
	case ExprSpread:
		return (*SpreadElement)(n.ptr).Idx1()
	case ExprStringLit:
		return (*StringLiteral)(n.ptr).Idx1()
	case ExprSuper:
		return (*SuperExpression)(n.ptr).Idx1()
	case ExprThis:
		return (*ThisExpression)(n.ptr).Idx1()
	case ExprTmplLit:
		return (*TemplateLiteral)(n.ptr).Idx1()
	case ExprUnary:
		return (*UnaryExpression)(n.ptr).Idx1()
	case ExprUpdate:
		return (*UpdateExpression)(n.ptr).Idx1()
	case ExprVarDeclarator:
		return (*VariableDeclarator)(n.ptr).Idx1()
	case ExprYield:
		return (*YieldExpression)(n.ptr).Idx1()
	}
	return 0
}

func (n *Expression) Unwrap() VisitableNode {
	if n == nil {
		return nil
	}
	switch n.kind {
	case ExprArrayLit:
		return (*ArrayLiteral)(n.ptr)
	case ExprArrowFuncLit:
		return (*ArrowFunctionLiteral)(n.ptr)
	case ExprAssign:
		return (*AssignExpression)(n.ptr)
	case ExprAwait:
		return (*AwaitExpression)(n.ptr)
	case ExprBigIntLit:
		return (*BigIntLiteral)(n.ptr)
	case ExprBinary:
		return (*BinaryExpression)(n.ptr)
	case ExprBoolLit:
		return (*BooleanLiteral)(n.ptr)
	case ExprCall:
		return (*CallExpression)(n.ptr)
	case ExprClassLit:
		return (*ClassLiteral)(n.ptr)
	case ExprConditional:
		return (*ConditionalExpression)(n.ptr)
	case ExprFuncLit:
		return (*FunctionLiteral)(n.ptr)
	case ExprIdentifier:
		return (*Identifier)(n.ptr)
	case ExprInvalid:
		return (*InvalidExpression)(n.ptr)
	case ExprLogical:
		return (*LogicalExpression)(n.ptr)
	case ExprMember:
		return (*MemberExpression)(n.ptr)
	case ExprMetaProp:
		return (*MetaProperty)(n.ptr)
	case ExprNew:
		return (*NewExpression)(n.ptr)
	case ExprNullLit:
		return (*NullLiteral)(n.ptr)
	case ExprNumberLit:
		return (*NumberLiteral)(n.ptr)
	case ExprObjectLit:
		return (*ObjectLiteral)(n.ptr)
	case ExprOptional:
		return (*Optional)(n.ptr)
	case ExprOptionalChain:
		return (*OptionalChain)(n.ptr)
	case ExprPrivDot:
		return (*PrivateDotExpression)(n.ptr)
	case ExprPrivIdentifier:
		return (*PrivateIdentifier)(n.ptr)
	case ExprRegExpLit:
		return (*RegExpLiteral)(n.ptr)
	case ExprSequence:
		return (*SequenceExpression)(n.ptr)
	case ExprSpread:
		return (*SpreadElement)(n.ptr)
	case ExprStringLit:
		return (*StringLiteral)(n.ptr)
	case ExprSuper:
		return (*SuperExpression)(n.ptr)
	case ExprThis:
		return (*ThisExpression)(n.ptr)
	case ExprTmplLit:
		return (*TemplateLiteral)(n.ptr)
	case ExprUnary:
		return (*UnaryExpression)(n.ptr)
	case ExprUpdate:
		return (*UpdateExpression)(n.ptr)
	case ExprVarDeclarator:
		return (*VariableDeclarator)(n.ptr)
	case ExprYield:
		return (*YieldExpression)(n.ptr)
	}
	return nil
}

// ---- ForInto tagged union ----

type ForIntoKind uint8

const (
	ForIntoNone ForIntoKind = iota
	ForIntoPattern
	ForIntoVarDecl
)

func (k ForIntoKind) String() string {
	switch k {
	case ForIntoNone:
		return "ForIntoNone"
	case ForIntoPattern:
		return "ForIntoPattern"
	case ForIntoVarDecl:
		return "ForIntoVarDecl"
	}
	return "ForIntoKind(?)"
}

func (n *ForInto) Kind() ForIntoKind { return n.kind }
func (n *ForInto) IsNone() bool      { return n.kind == ForIntoNone }

func NewPatternForInto(n *Pattern) ForInto {
	return ForInto{kind: ForIntoPattern, ptr: unsafe.Pointer(n)}
}

func (n *ForInto) Pattern() (*Pattern, bool) {
	if n.kind == ForIntoPattern {
		return (*Pattern)(n.ptr), true
	}
	return nil, false
}

func (n *ForInto) MustPattern() *Pattern {
	if n.kind != ForIntoPattern {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*Pattern)(n.ptr)
}

func (n *ForInto) IsPattern() bool {
	return n.kind == ForIntoPattern
}

func NewVarDeclForInto(n *VariableDeclaration) ForInto {
	return ForInto{kind: ForIntoVarDecl, ptr: unsafe.Pointer(n)}
}

func (n *ForInto) VarDecl() (*VariableDeclaration, bool) {
	if n.kind == ForIntoVarDecl {
		return (*VariableDeclaration)(n.ptr), true
	}
	return nil, false
}

func (n *ForInto) MustVarDecl() *VariableDeclaration {
	if n.kind != ForIntoVarDecl {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*VariableDeclaration)(n.ptr)
}

func (n *ForInto) IsVarDecl() bool {
	return n.kind == ForIntoVarDecl
}

func (n *ForInto) Idx0() Idx {
	switch n.kind {
	case ForIntoPattern:
		return (*Pattern)(n.ptr).Idx0()
	case ForIntoVarDecl:
		return (*VariableDeclaration)(n.ptr).Idx0()
	}
	return 0
}

func (n *ForInto) Idx1() Idx {
	switch n.kind {
	case ForIntoPattern:
		return (*Pattern)(n.ptr).Idx1()
	case ForIntoVarDecl:
		return (*VariableDeclaration)(n.ptr).Idx1()
	}
	return 0
}

func (n *ForInto) Unwrap() VisitableNode {
	if n == nil {
		return nil
	}
	switch n.kind {
	case ForIntoPattern:
		return (*Pattern)(n.ptr)
	case ForIntoVarDecl:
		return (*VariableDeclaration)(n.ptr)
	}
	return nil
}

// ---- ForLoopInitializer tagged union ----

type ForInitKind uint8

const (
	ForInitNone ForInitKind = iota
	ForInitExpr
	ForInitVarDecl
)

func (k ForInitKind) String() string {
	switch k {
	case ForInitNone:
		return "ForInitNone"
	case ForInitExpr:
		return "ForInitExpr"
	case ForInitVarDecl:
		return "ForInitVarDecl"
	}
	return "ForInitKind(?)"
}

func (n *ForLoopInitializer) Kind() ForInitKind { return n.kind }
func (n *ForLoopInitializer) IsNone() bool      { return n.kind == ForInitNone }

func NewExprForInit(n *Expression) ForLoopInitializer {
	return ForLoopInitializer{kind: ForInitExpr, ptr: unsafe.Pointer(n)}
}

func (n *ForLoopInitializer) Expr() (*Expression, bool) {
	if n.kind == ForInitExpr {
		return (*Expression)(n.ptr), true
	}
	return nil, false
}

func (n *ForLoopInitializer) MustExpr() *Expression {
	if n.kind != ForInitExpr {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*Expression)(n.ptr)
}

func (n *ForLoopInitializer) IsExpr() bool {
	return n.kind == ForInitExpr
}

func NewVarDeclForInit(n *VariableDeclaration) ForLoopInitializer {
	return ForLoopInitializer{kind: ForInitVarDecl, ptr: unsafe.Pointer(n)}
}

func (n *ForLoopInitializer) VarDecl() (*VariableDeclaration, bool) {
	if n.kind == ForInitVarDecl {
		return (*VariableDeclaration)(n.ptr), true
	}
	return nil, false
}

func (n *ForLoopInitializer) MustVarDecl() *VariableDeclaration {
	if n.kind != ForInitVarDecl {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*VariableDeclaration)(n.ptr)
}

func (n *ForLoopInitializer) IsVarDecl() bool {
	return n.kind == ForInitVarDecl
}

func (n *ForLoopInitializer) Idx0() Idx {
	switch n.kind {
	case ForInitExpr:
		return (*Expression)(n.ptr).Idx0()
	case ForInitVarDecl:
		return (*VariableDeclaration)(n.ptr).Idx0()
	}
	return 0
}

func (n *ForLoopInitializer) Idx1() Idx {
	switch n.kind {
	case ForInitExpr:
		return (*Expression)(n.ptr).Idx1()
	case ForInitVarDecl:
		return (*VariableDeclaration)(n.ptr).Idx1()
	}
	return 0
}

func (n *ForLoopInitializer) Unwrap() VisitableNode {
	if n == nil {
		return nil
	}
	switch n.kind {
	case ForInitExpr:
		return (*Expression)(n.ptr)
	case ForInitVarDecl:
		return (*VariableDeclaration)(n.ptr)
	}
	return nil
}

// ---- MemberProperty tagged union ----

type MemPropKind uint8

const (
	MemPropNone MemPropKind = iota
	MemPropComputed
	MemPropIdentifier
)

func (k MemPropKind) String() string {
	switch k {
	case MemPropNone:
		return "MemPropNone"
	case MemPropComputed:
		return "MemPropComputed"
	case MemPropIdentifier:
		return "MemPropIdentifier"
	}
	return "MemPropKind(?)"
}

func (n *MemberProperty) Kind() MemPropKind { return n.kind }
func (n *MemberProperty) IsNone() bool      { return n.kind == MemPropNone }

func NewComputedMemProp(n *ComputedProperty) MemberProperty {
	return MemberProperty{kind: MemPropComputed, ptr: unsafe.Pointer(n)}
}

func (n *MemberProperty) Computed() (*ComputedProperty, bool) {
	if n.kind == MemPropComputed {
		return (*ComputedProperty)(n.ptr), true
	}
	return nil, false
}

func (n *MemberProperty) MustComputed() *ComputedProperty {
	if n.kind != MemPropComputed {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ComputedProperty)(n.ptr)
}

func (n *MemberProperty) IsComputed() bool {
	return n.kind == MemPropComputed
}

func NewIdentifierMemProp(n *Identifier) MemberProperty {
	return MemberProperty{kind: MemPropIdentifier, ptr: unsafe.Pointer(n)}
}

func (n *MemberProperty) Identifier() (*Identifier, bool) {
	if n.kind == MemPropIdentifier {
		return (*Identifier)(n.ptr), true
	}
	return nil, false
}

func (n *MemberProperty) MustIdentifier() *Identifier {
	if n.kind != MemPropIdentifier {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*Identifier)(n.ptr)
}

func (n *MemberProperty) IsIdentifier() bool {
	return n.kind == MemPropIdentifier
}

func (n *MemberProperty) Idx0() Idx {
	switch n.kind {
	case MemPropComputed:
		return (*ComputedProperty)(n.ptr).Idx0()
	case MemPropIdentifier:
		return (*Identifier)(n.ptr).Idx0()
	}
	return 0
}

func (n *MemberProperty) Idx1() Idx {
	switch n.kind {
	case MemPropComputed:
		return (*ComputedProperty)(n.ptr).Idx1()
	case MemPropIdentifier:
		return (*Identifier)(n.ptr).Idx1()
	}
	return 0
}

func (n *MemberProperty) Unwrap() VisitableNode {
	if n == nil {
		return nil
	}
	switch n.kind {
	case MemPropComputed:
		return (*ComputedProperty)(n.ptr)
	case MemPropIdentifier:
		return (*Identifier)(n.ptr)
	}
	return nil
}

// ---- Pattern tagged union ----

type PatternKind uint8

const (
	PatternNone PatternKind = iota
	PatternArrayPat
	PatternAssign
	PatternIdentifier
	PatternInvalid
	PatternMember
	PatternObjectPat
	PatternPrivDot
)

func (k PatternKind) String() string {
	switch k {
	case PatternNone:
		return "PatternNone"
	case PatternArrayPat:
		return "PatternArrayPat"
	case PatternAssign:
		return "PatternAssign"
	case PatternIdentifier:
		return "PatternIdentifier"
	case PatternInvalid:
		return "PatternInvalid"
	case PatternMember:
		return "PatternMember"
	case PatternObjectPat:
		return "PatternObjectPat"
	case PatternPrivDot:
		return "PatternPrivDot"
	}
	return "PatternKind(?)"
}

func (n *Pattern) Kind() PatternKind { return n.kind }
func (n *Pattern) IsNone() bool      { return n.kind == PatternNone }

func NewArrayPatPattern(n *ArrayPattern) Pattern {
	return Pattern{kind: PatternArrayPat, ptr: unsafe.Pointer(n)}
}

func (n *Pattern) ArrayPat() (*ArrayPattern, bool) {
	if n.kind == PatternArrayPat {
		return (*ArrayPattern)(n.ptr), true
	}
	return nil, false
}

func (n *Pattern) MustArrayPat() *ArrayPattern {
	if n.kind != PatternArrayPat {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ArrayPattern)(n.ptr)
}

func (n *Pattern) IsArrayPat() bool {
	return n.kind == PatternArrayPat
}

func NewAssignPattern(n *AssignmentPattern) Pattern {
	return Pattern{kind: PatternAssign, ptr: unsafe.Pointer(n)}
}

func (n *Pattern) Assign() (*AssignmentPattern, bool) {
	if n.kind == PatternAssign {
		return (*AssignmentPattern)(n.ptr), true
	}
	return nil, false
}

func (n *Pattern) MustAssign() *AssignmentPattern {
	if n.kind != PatternAssign {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*AssignmentPattern)(n.ptr)
}

func (n *Pattern) IsAssign() bool {
	return n.kind == PatternAssign
}

func NewIdentifierPattern(n *Identifier) Pattern {
	return Pattern{kind: PatternIdentifier, ptr: unsafe.Pointer(n)}
}

func (n *Pattern) Identifier() (*Identifier, bool) {
	if n.kind == PatternIdentifier {
		return (*Identifier)(n.ptr), true
	}
	return nil, false
}

func (n *Pattern) MustIdentifier() *Identifier {
	if n.kind != PatternIdentifier {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*Identifier)(n.ptr)
}

func (n *Pattern) IsIdentifier() bool {
	return n.kind == PatternIdentifier
}

func NewInvalidPattern(n *InvalidExpression) Pattern {
	return Pattern{kind: PatternInvalid, ptr: unsafe.Pointer(n)}
}

func (n *Pattern) Invalid() (*InvalidExpression, bool) {
	if n.kind == PatternInvalid {
		return (*InvalidExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Pattern) MustInvalid() *InvalidExpression {
	if n.kind != PatternInvalid {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*InvalidExpression)(n.ptr)
}

func (n *Pattern) IsInvalid() bool {
	return n.kind == PatternInvalid
}

func NewMemberPattern(n *MemberExpression) Pattern {
	return Pattern{kind: PatternMember, ptr: unsafe.Pointer(n)}
}

func (n *Pattern) Member() (*MemberExpression, bool) {
	if n.kind == PatternMember {
		return (*MemberExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Pattern) MustMember() *MemberExpression {
	if n.kind != PatternMember {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*MemberExpression)(n.ptr)
}

func (n *Pattern) IsMember() bool {
	return n.kind == PatternMember
}

func NewObjectPatPattern(n *ObjectPattern) Pattern {
	return Pattern{kind: PatternObjectPat, ptr: unsafe.Pointer(n)}
}

func (n *Pattern) ObjectPat() (*ObjectPattern, bool) {
	if n.kind == PatternObjectPat {
		return (*ObjectPattern)(n.ptr), true
	}
	return nil, false
}

func (n *Pattern) MustObjectPat() *ObjectPattern {
	if n.kind != PatternObjectPat {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ObjectPattern)(n.ptr)
}

func (n *Pattern) IsObjectPat() bool {
	return n.kind == PatternObjectPat
}

func NewPrivDotPattern(n *PrivateDotExpression) Pattern {
	return Pattern{kind: PatternPrivDot, ptr: unsafe.Pointer(n)}
}

func (n *Pattern) PrivDot() (*PrivateDotExpression, bool) {
	if n.kind == PatternPrivDot {
		return (*PrivateDotExpression)(n.ptr), true
	}
	return nil, false
}

func (n *Pattern) MustPrivDot() *PrivateDotExpression {
	if n.kind != PatternPrivDot {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*PrivateDotExpression)(n.ptr)
}

func (n *Pattern) IsPrivDot() bool {
	return n.kind == PatternPrivDot
}

func (n *Pattern) Idx0() Idx {
	switch n.kind {
	case PatternArrayPat:
		return (*ArrayPattern)(n.ptr).Idx0()
	case PatternAssign:
		return (*AssignmentPattern)(n.ptr).Idx0()
	case PatternIdentifier:
		return (*Identifier)(n.ptr).Idx0()
	case PatternInvalid:
		return (*InvalidExpression)(n.ptr).Idx0()
	case PatternMember:
		return (*MemberExpression)(n.ptr).Idx0()
	case PatternObjectPat:
		return (*ObjectPattern)(n.ptr).Idx0()
	case PatternPrivDot:
		return (*PrivateDotExpression)(n.ptr).Idx0()
	}
	return 0
}

func (n *Pattern) Idx1() Idx {
	switch n.kind {
	case PatternArrayPat:
		return (*ArrayPattern)(n.ptr).Idx1()
	case PatternAssign:
		return (*AssignmentPattern)(n.ptr).Idx1()
	case PatternIdentifier:
		return (*Identifier)(n.ptr).Idx1()
	case PatternInvalid:
		return (*InvalidExpression)(n.ptr).Idx1()
	case PatternMember:
		return (*MemberExpression)(n.ptr).Idx1()
	case PatternObjectPat:
		return (*ObjectPattern)(n.ptr).Idx1()
	case PatternPrivDot:
		return (*PrivateDotExpression)(n.ptr).Idx1()
	}
	return 0
}

func (n *Pattern) Unwrap() VisitableNode {
	if n == nil {
		return nil
	}
	switch n.kind {
	case PatternArrayPat:
		return (*ArrayPattern)(n.ptr)
	case PatternAssign:
		return (*AssignmentPattern)(n.ptr)
	case PatternIdentifier:
		return (*Identifier)(n.ptr)
	case PatternInvalid:
		return (*InvalidExpression)(n.ptr)
	case PatternMember:
		return (*MemberExpression)(n.ptr)
	case PatternObjectPat:
		return (*ObjectPattern)(n.ptr)
	case PatternPrivDot:
		return (*PrivateDotExpression)(n.ptr)
	}
	return nil
}

// ---- PatternProperty tagged union ----

type PatPropKind uint8

const (
	PatPropNone PatPropKind = iota
	PatPropKeyValue
	PatPropShorthand
)

func (k PatPropKind) String() string {
	switch k {
	case PatPropNone:
		return "PatPropNone"
	case PatPropKeyValue:
		return "PatPropKeyValue"
	case PatPropShorthand:
		return "PatPropShorthand"
	}
	return "PatPropKind(?)"
}

func (n *PatternProperty) Kind() PatPropKind { return n.kind }
func (n *PatternProperty) IsNone() bool      { return n.kind == PatPropNone }

func NewKeyValuePatProp(n *PatternKeyValue) PatternProperty {
	return PatternProperty{kind: PatPropKeyValue, ptr: unsafe.Pointer(n)}
}

func (n *PatternProperty) KeyValue() (*PatternKeyValue, bool) {
	if n.kind == PatPropKeyValue {
		return (*PatternKeyValue)(n.ptr), true
	}
	return nil, false
}

func (n *PatternProperty) MustKeyValue() *PatternKeyValue {
	if n.kind != PatPropKeyValue {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*PatternKeyValue)(n.ptr)
}

func (n *PatternProperty) IsKeyValue() bool {
	return n.kind == PatPropKeyValue
}

func NewShorthandPatProp(n *PatternShorthand) PatternProperty {
	return PatternProperty{kind: PatPropShorthand, ptr: unsafe.Pointer(n)}
}

func (n *PatternProperty) Shorthand() (*PatternShorthand, bool) {
	if n.kind == PatPropShorthand {
		return (*PatternShorthand)(n.ptr), true
	}
	return nil, false
}

func (n *PatternProperty) MustShorthand() *PatternShorthand {
	if n.kind != PatPropShorthand {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*PatternShorthand)(n.ptr)
}

func (n *PatternProperty) IsShorthand() bool {
	return n.kind == PatPropShorthand
}

func (n *PatternProperty) Idx0() Idx {
	switch n.kind {
	case PatPropKeyValue:
		return (*PatternKeyValue)(n.ptr).Idx0()
	case PatPropShorthand:
		return (*PatternShorthand)(n.ptr).Idx0()
	}
	return 0
}

func (n *PatternProperty) Idx1() Idx {
	switch n.kind {
	case PatPropKeyValue:
		return (*PatternKeyValue)(n.ptr).Idx1()
	case PatPropShorthand:
		return (*PatternShorthand)(n.ptr).Idx1()
	}
	return 0
}

func (n *PatternProperty) Unwrap() VisitableNode {
	if n == nil {
		return nil
	}
	switch n.kind {
	case PatPropKeyValue:
		return (*PatternKeyValue)(n.ptr)
	case PatPropShorthand:
		return (*PatternShorthand)(n.ptr)
	}
	return nil
}

// ---- Property tagged union ----

type PropKind uint8

const (
	PropNone PropKind = iota
	PropGetter
	PropKeyValue
	PropMethod
	PropSetter
	PropShort
	PropSpread
)

func (k PropKind) String() string {
	switch k {
	case PropNone:
		return "PropNone"
	case PropGetter:
		return "PropGetter"
	case PropKeyValue:
		return "PropKeyValue"
	case PropMethod:
		return "PropMethod"
	case PropSetter:
		return "PropSetter"
	case PropShort:
		return "PropShort"
	case PropSpread:
		return "PropSpread"
	}
	return "PropKind(?)"
}

func (n *Property) Kind() PropKind { return n.kind }
func (n *Property) IsNone() bool   { return n.kind == PropNone }

func NewGetterProp(n *PropertyGetter) Property {
	return Property{kind: PropGetter, ptr: unsafe.Pointer(n)}
}

func (n *Property) Getter() (*PropertyGetter, bool) {
	if n.kind == PropGetter {
		return (*PropertyGetter)(n.ptr), true
	}
	return nil, false
}

func (n *Property) MustGetter() *PropertyGetter {
	if n.kind != PropGetter {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*PropertyGetter)(n.ptr)
}

func (n *Property) IsGetter() bool {
	return n.kind == PropGetter
}

func NewKeyValueProp(n *PropertyKeyValue) Property {
	return Property{kind: PropKeyValue, ptr: unsafe.Pointer(n)}
}

func (n *Property) KeyValue() (*PropertyKeyValue, bool) {
	if n.kind == PropKeyValue {
		return (*PropertyKeyValue)(n.ptr), true
	}
	return nil, false
}

func (n *Property) MustKeyValue() *PropertyKeyValue {
	if n.kind != PropKeyValue {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*PropertyKeyValue)(n.ptr)
}

func (n *Property) IsKeyValue() bool {
	return n.kind == PropKeyValue
}

func NewMethodProp(n *PropertyMethod) Property {
	return Property{kind: PropMethod, ptr: unsafe.Pointer(n)}
}

func (n *Property) Method() (*PropertyMethod, bool) {
	if n.kind == PropMethod {
		return (*PropertyMethod)(n.ptr), true
	}
	return nil, false
}

func (n *Property) MustMethod() *PropertyMethod {
	if n.kind != PropMethod {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*PropertyMethod)(n.ptr)
}

func (n *Property) IsMethod() bool {
	return n.kind == PropMethod
}

func NewSetterProp(n *PropertySetter) Property {
	return Property{kind: PropSetter, ptr: unsafe.Pointer(n)}
}

func (n *Property) Setter() (*PropertySetter, bool) {
	if n.kind == PropSetter {
		return (*PropertySetter)(n.ptr), true
	}
	return nil, false
}

func (n *Property) MustSetter() *PropertySetter {
	if n.kind != PropSetter {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*PropertySetter)(n.ptr)
}

func (n *Property) IsSetter() bool {
	return n.kind == PropSetter
}

func NewShortProp(n *PropertyShort) Property {
	return Property{kind: PropShort, ptr: unsafe.Pointer(n)}
}

func (n *Property) Short() (*PropertyShort, bool) {
	if n.kind == PropShort {
		return (*PropertyShort)(n.ptr), true
	}
	return nil, false
}

func (n *Property) MustShort() *PropertyShort {
	if n.kind != PropShort {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*PropertyShort)(n.ptr)
}

func (n *Property) IsShort() bool {
	return n.kind == PropShort
}

func NewSpreadProp(n *SpreadElement) Property {
	return Property{kind: PropSpread, ptr: unsafe.Pointer(n)}
}

func (n *Property) Spread() (*SpreadElement, bool) {
	if n.kind == PropSpread {
		return (*SpreadElement)(n.ptr), true
	}
	return nil, false
}

func (n *Property) MustSpread() *SpreadElement {
	if n.kind != PropSpread {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*SpreadElement)(n.ptr)
}

func (n *Property) IsSpread() bool {
	return n.kind == PropSpread
}

func (n *Property) Idx0() Idx {
	switch n.kind {
	case PropGetter:
		return (*PropertyGetter)(n.ptr).Idx0()
	case PropKeyValue:
		return (*PropertyKeyValue)(n.ptr).Idx0()
	case PropMethod:
		return (*PropertyMethod)(n.ptr).Idx0()
	case PropSetter:
		return (*PropertySetter)(n.ptr).Idx0()
	case PropShort:
		return (*PropertyShort)(n.ptr).Idx0()
	case PropSpread:
		return (*SpreadElement)(n.ptr).Idx0()
	}
	return 0
}

func (n *Property) Idx1() Idx {
	switch n.kind {
	case PropGetter:
		return (*PropertyGetter)(n.ptr).Idx1()
	case PropKeyValue:
		return (*PropertyKeyValue)(n.ptr).Idx1()
	case PropMethod:
		return (*PropertyMethod)(n.ptr).Idx1()
	case PropSetter:
		return (*PropertySetter)(n.ptr).Idx1()
	case PropShort:
		return (*PropertyShort)(n.ptr).Idx1()
	case PropSpread:
		return (*SpreadElement)(n.ptr).Idx1()
	}
	return 0
}

func (n *Property) Unwrap() VisitableNode {
	if n == nil {
		return nil
	}
	switch n.kind {
	case PropGetter:
		return (*PropertyGetter)(n.ptr)
	case PropKeyValue:
		return (*PropertyKeyValue)(n.ptr)
	case PropMethod:
		return (*PropertyMethod)(n.ptr)
	case PropSetter:
		return (*PropertySetter)(n.ptr)
	case PropShort:
		return (*PropertyShort)(n.ptr)
	case PropSpread:
		return (*SpreadElement)(n.ptr)
	}
	return nil
}

// ---- PropertyName tagged union ----

type PropNameKind uint8

const (
	PropNameNone PropNameKind = iota
	PropNameBigIntLit
	PropNameComputed
	PropNameNumberLit
	PropNamePrivIdentifier
	PropNameStringLit
)

func (k PropNameKind) String() string {
	switch k {
	case PropNameNone:
		return "PropNameNone"
	case PropNameBigIntLit:
		return "PropNameBigIntLit"
	case PropNameComputed:
		return "PropNameComputed"
	case PropNameNumberLit:
		return "PropNameNumberLit"
	case PropNamePrivIdentifier:
		return "PropNamePrivIdentifier"
	case PropNameStringLit:
		return "PropNameStringLit"
	}
	return "PropNameKind(?)"
}

func (n *PropertyName) Kind() PropNameKind { return n.kind }
func (n *PropertyName) IsNone() bool       { return n.kind == PropNameNone }

func NewBigIntLitPropName(n *BigIntLiteral) PropertyName {
	return PropertyName{kind: PropNameBigIntLit, ptr: unsafe.Pointer(n)}
}

func (n *PropertyName) BigIntLit() (*BigIntLiteral, bool) {
	if n.kind == PropNameBigIntLit {
		return (*BigIntLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *PropertyName) MustBigIntLit() *BigIntLiteral {
	if n.kind != PropNameBigIntLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*BigIntLiteral)(n.ptr)
}

func (n *PropertyName) IsBigIntLit() bool {
	return n.kind == PropNameBigIntLit
}

func NewComputedPropName(n *ComputedProperty) PropertyName {
	return PropertyName{kind: PropNameComputed, ptr: unsafe.Pointer(n)}
}

func (n *PropertyName) Computed() (*ComputedProperty, bool) {
	if n.kind == PropNameComputed {
		return (*ComputedProperty)(n.ptr), true
	}
	return nil, false
}

func (n *PropertyName) MustComputed() *ComputedProperty {
	if n.kind != PropNameComputed {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ComputedProperty)(n.ptr)
}

func (n *PropertyName) IsComputed() bool {
	return n.kind == PropNameComputed
}

func NewNumberLitPropName(n *NumberLiteral) PropertyName {
	return PropertyName{kind: PropNameNumberLit, ptr: unsafe.Pointer(n)}
}

func (n *PropertyName) NumberLit() (*NumberLiteral, bool) {
	if n.kind == PropNameNumberLit {
		return (*NumberLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *PropertyName) MustNumberLit() *NumberLiteral {
	if n.kind != PropNameNumberLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*NumberLiteral)(n.ptr)
}

func (n *PropertyName) IsNumberLit() bool {
	return n.kind == PropNameNumberLit
}

func NewPrivIdentifierPropName(n *PrivateIdentifier) PropertyName {
	return PropertyName{kind: PropNamePrivIdentifier, ptr: unsafe.Pointer(n)}
}

func (n *PropertyName) PrivIdentifier() (*PrivateIdentifier, bool) {
	if n.kind == PropNamePrivIdentifier {
		return (*PrivateIdentifier)(n.ptr), true
	}
	return nil, false
}

func (n *PropertyName) MustPrivIdentifier() *PrivateIdentifier {
	if n.kind != PropNamePrivIdentifier {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*PrivateIdentifier)(n.ptr)
}

func (n *PropertyName) IsPrivIdentifier() bool {
	return n.kind == PropNamePrivIdentifier
}

func NewStringLitPropName(n *StringLiteral) PropertyName {
	return PropertyName{kind: PropNameStringLit, ptr: unsafe.Pointer(n)}
}

func (n *PropertyName) StringLit() (*StringLiteral, bool) {
	if n.kind == PropNameStringLit {
		return (*StringLiteral)(n.ptr), true
	}
	return nil, false
}

func (n *PropertyName) MustStringLit() *StringLiteral {
	if n.kind != PropNameStringLit {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*StringLiteral)(n.ptr)
}

func (n *PropertyName) IsStringLit() bool {
	return n.kind == PropNameStringLit
}

func (n *PropertyName) Idx0() Idx {
	switch n.kind {
	case PropNameBigIntLit:
		return (*BigIntLiteral)(n.ptr).Idx0()
	case PropNameComputed:
		return (*ComputedProperty)(n.ptr).Idx0()
	case PropNameNumberLit:
		return (*NumberLiteral)(n.ptr).Idx0()
	case PropNamePrivIdentifier:
		return (*PrivateIdentifier)(n.ptr).Idx0()
	case PropNameStringLit:
		return (*StringLiteral)(n.ptr).Idx0()
	}
	return 0
}

func (n *PropertyName) Idx1() Idx {
	switch n.kind {
	case PropNameBigIntLit:
		return (*BigIntLiteral)(n.ptr).Idx1()
	case PropNameComputed:
		return (*ComputedProperty)(n.ptr).Idx1()
	case PropNameNumberLit:
		return (*NumberLiteral)(n.ptr).Idx1()
	case PropNamePrivIdentifier:
		return (*PrivateIdentifier)(n.ptr).Idx1()
	case PropNameStringLit:
		return (*StringLiteral)(n.ptr).Idx1()
	}
	return 0
}

func (n *PropertyName) Unwrap() VisitableNode {
	if n == nil {
		return nil
	}
	switch n.kind {
	case PropNameBigIntLit:
		return (*BigIntLiteral)(n.ptr)
	case PropNameComputed:
		return (*ComputedProperty)(n.ptr)
	case PropNameNumberLit:
		return (*NumberLiteral)(n.ptr)
	case PropNamePrivIdentifier:
		return (*PrivateIdentifier)(n.ptr)
	case PropNameStringLit:
		return (*StringLiteral)(n.ptr)
	}
	return nil
}

// ---- Statement tagged union ----

type StmtKind uint8

const (
	StmtNone StmtKind = iota
	StmtBad
	StmtBlock
	StmtBreak
	StmtCase
	StmtCatch
	StmtClassDecl
	StmtContinue
	StmtDebugger
	StmtDoWhile
	StmtEmpty
	StmtExpression
	StmtFor
	StmtForIn
	StmtForOf
	StmtFuncDecl
	StmtIf
	StmtLabelled
	StmtReturn
	StmtSwitch
	StmtThrow
	StmtTry
	StmtVarDecl
	StmtWhile
	StmtWith
)

func (k StmtKind) String() string {
	switch k {
	case StmtNone:
		return "StmtNone"
	case StmtBad:
		return "StmtBad"
	case StmtBlock:
		return "StmtBlock"
	case StmtBreak:
		return "StmtBreak"
	case StmtCase:
		return "StmtCase"
	case StmtCatch:
		return "StmtCatch"
	case StmtClassDecl:
		return "StmtClassDecl"
	case StmtContinue:
		return "StmtContinue"
	case StmtDebugger:
		return "StmtDebugger"
	case StmtDoWhile:
		return "StmtDoWhile"
	case StmtEmpty:
		return "StmtEmpty"
	case StmtExpression:
		return "StmtExpression"
	case StmtFor:
		return "StmtFor"
	case StmtForIn:
		return "StmtForIn"
	case StmtForOf:
		return "StmtForOf"
	case StmtFuncDecl:
		return "StmtFuncDecl"
	case StmtIf:
		return "StmtIf"
	case StmtLabelled:
		return "StmtLabelled"
	case StmtReturn:
		return "StmtReturn"
	case StmtSwitch:
		return "StmtSwitch"
	case StmtThrow:
		return "StmtThrow"
	case StmtTry:
		return "StmtTry"
	case StmtVarDecl:
		return "StmtVarDecl"
	case StmtWhile:
		return "StmtWhile"
	case StmtWith:
		return "StmtWith"
	}
	return "StmtKind(?)"
}

func (n *Statement) Kind() StmtKind { return n.kind }
func (n *Statement) IsNone() bool   { return n.kind == StmtNone }

func NewBadStmt(n *BadStatement) Statement {
	return Statement{kind: StmtBad, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Bad() (*BadStatement, bool) {
	if n.kind == StmtBad {
		return (*BadStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustBad() *BadStatement {
	if n.kind != StmtBad {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*BadStatement)(n.ptr)
}

func (n *Statement) IsBad() bool {
	return n.kind == StmtBad
}

func NewBlockStmt(n *BlockStatement) Statement {
	return Statement{kind: StmtBlock, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Block() (*BlockStatement, bool) {
	if n.kind == StmtBlock {
		return (*BlockStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustBlock() *BlockStatement {
	if n.kind != StmtBlock {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*BlockStatement)(n.ptr)
}

func (n *Statement) IsBlock() bool {
	return n.kind == StmtBlock
}

func NewBreakStmt(n *BreakStatement) Statement {
	return Statement{kind: StmtBreak, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Break() (*BreakStatement, bool) {
	if n.kind == StmtBreak {
		return (*BreakStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustBreak() *BreakStatement {
	if n.kind != StmtBreak {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*BreakStatement)(n.ptr)
}

func (n *Statement) IsBreak() bool {
	return n.kind == StmtBreak
}

func NewCaseStmt(n *CaseStatement) Statement {
	return Statement{kind: StmtCase, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Case() (*CaseStatement, bool) {
	if n.kind == StmtCase {
		return (*CaseStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustCase() *CaseStatement {
	if n.kind != StmtCase {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*CaseStatement)(n.ptr)
}

func (n *Statement) IsCase() bool {
	return n.kind == StmtCase
}

func NewCatchStmt(n *CatchStatement) Statement {
	return Statement{kind: StmtCatch, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Catch() (*CatchStatement, bool) {
	if n.kind == StmtCatch {
		return (*CatchStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustCatch() *CatchStatement {
	if n.kind != StmtCatch {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*CatchStatement)(n.ptr)
}

func (n *Statement) IsCatch() bool {
	return n.kind == StmtCatch
}

func NewClassDeclStmt(n *ClassDeclaration) Statement {
	return Statement{kind: StmtClassDecl, ptr: unsafe.Pointer(n)}
}

func (n *Statement) ClassDecl() (*ClassDeclaration, bool) {
	if n.kind == StmtClassDecl {
		return (*ClassDeclaration)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustClassDecl() *ClassDeclaration {
	if n.kind != StmtClassDecl {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ClassDeclaration)(n.ptr)
}

func (n *Statement) IsClassDecl() bool {
	return n.kind == StmtClassDecl
}

func NewContinueStmt(n *ContinueStatement) Statement {
	return Statement{kind: StmtContinue, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Continue() (*ContinueStatement, bool) {
	if n.kind == StmtContinue {
		return (*ContinueStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustContinue() *ContinueStatement {
	if n.kind != StmtContinue {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ContinueStatement)(n.ptr)
}

func (n *Statement) IsContinue() bool {
	return n.kind == StmtContinue
}

func NewDebuggerStmt(n *DebuggerStatement) Statement {
	return Statement{kind: StmtDebugger, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Debugger() (*DebuggerStatement, bool) {
	if n.kind == StmtDebugger {
		return (*DebuggerStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustDebugger() *DebuggerStatement {
	if n.kind != StmtDebugger {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*DebuggerStatement)(n.ptr)
}

func (n *Statement) IsDebugger() bool {
	return n.kind == StmtDebugger
}

func NewDoWhileStmt(n *DoWhileStatement) Statement {
	return Statement{kind: StmtDoWhile, ptr: unsafe.Pointer(n)}
}

func (n *Statement) DoWhile() (*DoWhileStatement, bool) {
	if n.kind == StmtDoWhile {
		return (*DoWhileStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustDoWhile() *DoWhileStatement {
	if n.kind != StmtDoWhile {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*DoWhileStatement)(n.ptr)
}

func (n *Statement) IsDoWhile() bool {
	return n.kind == StmtDoWhile
}

func NewEmptyStmt(n *EmptyStatement) Statement {
	return Statement{kind: StmtEmpty, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Empty() (*EmptyStatement, bool) {
	if n.kind == StmtEmpty {
		return (*EmptyStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustEmpty() *EmptyStatement {
	if n.kind != StmtEmpty {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*EmptyStatement)(n.ptr)
}

func (n *Statement) IsEmpty() bool {
	return n.kind == StmtEmpty
}

func NewExpressionStmt(n *ExpressionStatement) Statement {
	return Statement{kind: StmtExpression, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Expression() (*ExpressionStatement, bool) {
	if n.kind == StmtExpression {
		return (*ExpressionStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustExpression() *ExpressionStatement {
	if n.kind != StmtExpression {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ExpressionStatement)(n.ptr)
}

func (n *Statement) IsExpression() bool {
	return n.kind == StmtExpression
}

func NewForStmt(n *ForStatement) Statement {
	return Statement{kind: StmtFor, ptr: unsafe.Pointer(n)}
}

func (n *Statement) For() (*ForStatement, bool) {
	if n.kind == StmtFor {
		return (*ForStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustFor() *ForStatement {
	if n.kind != StmtFor {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ForStatement)(n.ptr)
}

func (n *Statement) IsFor() bool {
	return n.kind == StmtFor
}

func NewForInStmt(n *ForInStatement) Statement {
	return Statement{kind: StmtForIn, ptr: unsafe.Pointer(n)}
}

func (n *Statement) ForIn() (*ForInStatement, bool) {
	if n.kind == StmtForIn {
		return (*ForInStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustForIn() *ForInStatement {
	if n.kind != StmtForIn {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ForInStatement)(n.ptr)
}

func (n *Statement) IsForIn() bool {
	return n.kind == StmtForIn
}

func NewForOfStmt(n *ForOfStatement) Statement {
	return Statement{kind: StmtForOf, ptr: unsafe.Pointer(n)}
}

func (n *Statement) ForOf() (*ForOfStatement, bool) {
	if n.kind == StmtForOf {
		return (*ForOfStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustForOf() *ForOfStatement {
	if n.kind != StmtForOf {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ForOfStatement)(n.ptr)
}

func (n *Statement) IsForOf() bool {
	return n.kind == StmtForOf
}

func NewFuncDeclStmt(n *FunctionDeclaration) Statement {
	return Statement{kind: StmtFuncDecl, ptr: unsafe.Pointer(n)}
}

func (n *Statement) FuncDecl() (*FunctionDeclaration, bool) {
	if n.kind == StmtFuncDecl {
		return (*FunctionDeclaration)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustFuncDecl() *FunctionDeclaration {
	if n.kind != StmtFuncDecl {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*FunctionDeclaration)(n.ptr)
}

func (n *Statement) IsFuncDecl() bool {
	return n.kind == StmtFuncDecl
}

func NewIfStmt(n *IfStatement) Statement {
	return Statement{kind: StmtIf, ptr: unsafe.Pointer(n)}
}

func (n *Statement) If() (*IfStatement, bool) {
	if n.kind == StmtIf {
		return (*IfStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustIf() *IfStatement {
	if n.kind != StmtIf {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*IfStatement)(n.ptr)
}

func (n *Statement) IsIf() bool {
	return n.kind == StmtIf
}

func NewLabelledStmt(n *LabelledStatement) Statement {
	return Statement{kind: StmtLabelled, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Labelled() (*LabelledStatement, bool) {
	if n.kind == StmtLabelled {
		return (*LabelledStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustLabelled() *LabelledStatement {
	if n.kind != StmtLabelled {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*LabelledStatement)(n.ptr)
}

func (n *Statement) IsLabelled() bool {
	return n.kind == StmtLabelled
}

func NewReturnStmt(n *ReturnStatement) Statement {
	return Statement{kind: StmtReturn, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Return() (*ReturnStatement, bool) {
	if n.kind == StmtReturn {
		return (*ReturnStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustReturn() *ReturnStatement {
	if n.kind != StmtReturn {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ReturnStatement)(n.ptr)
}

func (n *Statement) IsReturn() bool {
	return n.kind == StmtReturn
}

func NewSwitchStmt(n *SwitchStatement) Statement {
	return Statement{kind: StmtSwitch, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Switch() (*SwitchStatement, bool) {
	if n.kind == StmtSwitch {
		return (*SwitchStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustSwitch() *SwitchStatement {
	if n.kind != StmtSwitch {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*SwitchStatement)(n.ptr)
}

func (n *Statement) IsSwitch() bool {
	return n.kind == StmtSwitch
}

func NewThrowStmt(n *ThrowStatement) Statement {
	return Statement{kind: StmtThrow, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Throw() (*ThrowStatement, bool) {
	if n.kind == StmtThrow {
		return (*ThrowStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustThrow() *ThrowStatement {
	if n.kind != StmtThrow {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*ThrowStatement)(n.ptr)
}

func (n *Statement) IsThrow() bool {
	return n.kind == StmtThrow
}

func NewTryStmt(n *TryStatement) Statement {
	return Statement{kind: StmtTry, ptr: unsafe.Pointer(n)}
}

func (n *Statement) Try() (*TryStatement, bool) {
	if n.kind == StmtTry {
		return (*TryStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustTry() *TryStatement {
	if n.kind != StmtTry {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*TryStatement)(n.ptr)
}

func (n *Statement) IsTry() bool {
	return n.kind == StmtTry
}

func NewVarDeclStmt(n *VariableDeclaration) Statement {
	return Statement{kind: StmtVarDecl, ptr: unsafe.Pointer(n)}
}

func (n *Statement) VarDecl() (*VariableDeclaration, bool) {
	if n.kind == StmtVarDecl {
		return (*VariableDeclaration)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustVarDecl() *VariableDeclaration {
	if n.kind != StmtVarDecl {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*VariableDeclaration)(n.ptr)
}

func (n *Statement) IsVarDecl() bool {
	return n.kind == StmtVarDecl
}

func NewWhileStmt(n *WhileStatement) Statement {
	return Statement{kind: StmtWhile, ptr: unsafe.Pointer(n)}
}

func (n *Statement) While() (*WhileStatement, bool) {
	if n.kind == StmtWhile {
		return (*WhileStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustWhile() *WhileStatement {
	if n.kind != StmtWhile {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*WhileStatement)(n.ptr)
}

func (n *Statement) IsWhile() bool {
	return n.kind == StmtWhile
}

func NewWithStmt(n *WithStatement) Statement {
	return Statement{kind: StmtWith, ptr: unsafe.Pointer(n)}
}

func (n *Statement) With() (*WithStatement, bool) {
	if n.kind == StmtWith {
		return (*WithStatement)(n.ptr), true
	}
	return nil, false
}

func (n *Statement) MustWith() *WithStatement {
	if n.kind != StmtWith {
		panic("unexpected kind: " + n.kind.String())
	}
	return (*WithStatement)(n.ptr)
}

func (n *Statement) IsWith() bool {
	return n.kind == StmtWith
}

func (n *Statement) Idx0() Idx {
	switch n.kind {
	case StmtBad:
		return (*BadStatement)(n.ptr).Idx0()
	case StmtBlock:
		return (*BlockStatement)(n.ptr).Idx0()
	case StmtBreak:
		return (*BreakStatement)(n.ptr).Idx0()
	case StmtCase:
		return (*CaseStatement)(n.ptr).Idx0()
	case StmtCatch:
		return (*CatchStatement)(n.ptr).Idx0()
	case StmtClassDecl:
		return (*ClassDeclaration)(n.ptr).Idx0()
	case StmtContinue:
		return (*ContinueStatement)(n.ptr).Idx0()
	case StmtDebugger:
		return (*DebuggerStatement)(n.ptr).Idx0()
	case StmtDoWhile:
		return (*DoWhileStatement)(n.ptr).Idx0()
	case StmtEmpty:
		return (*EmptyStatement)(n.ptr).Idx0()
	case StmtExpression:
		return (*ExpressionStatement)(n.ptr).Idx0()
	case StmtFor:
		return (*ForStatement)(n.ptr).Idx0()
	case StmtForIn:
		return (*ForInStatement)(n.ptr).Idx0()
	case StmtForOf:
		return (*ForOfStatement)(n.ptr).Idx0()
	case StmtFuncDecl:
		return (*FunctionDeclaration)(n.ptr).Idx0()
	case StmtIf:
		return (*IfStatement)(n.ptr).Idx0()
	case StmtLabelled:
		return (*LabelledStatement)(n.ptr).Idx0()
	case StmtReturn:
		return (*ReturnStatement)(n.ptr).Idx0()
	case StmtSwitch:
		return (*SwitchStatement)(n.ptr).Idx0()
	case StmtThrow:
		return (*ThrowStatement)(n.ptr).Idx0()
	case StmtTry:
		return (*TryStatement)(n.ptr).Idx0()
	case StmtVarDecl:
		return (*VariableDeclaration)(n.ptr).Idx0()
	case StmtWhile:
		return (*WhileStatement)(n.ptr).Idx0()
	case StmtWith:
		return (*WithStatement)(n.ptr).Idx0()
	}
	return 0
}

func (n *Statement) Idx1() Idx {
	switch n.kind {
	case StmtBad:
		return (*BadStatement)(n.ptr).Idx1()
	case StmtBlock:
		return (*BlockStatement)(n.ptr).Idx1()
	case StmtBreak:
		return (*BreakStatement)(n.ptr).Idx1()
	case StmtCase:
		return (*CaseStatement)(n.ptr).Idx1()
	case StmtCatch:
		return (*CatchStatement)(n.ptr).Idx1()
	case StmtClassDecl:
		return (*ClassDeclaration)(n.ptr).Idx1()
	case StmtContinue:
		return (*ContinueStatement)(n.ptr).Idx1()
	case StmtDebugger:
		return (*DebuggerStatement)(n.ptr).Idx1()
	case StmtDoWhile:
		return (*DoWhileStatement)(n.ptr).Idx1()
	case StmtEmpty:
		return (*EmptyStatement)(n.ptr).Idx1()
	case StmtExpression:
		return (*ExpressionStatement)(n.ptr).Idx1()
	case StmtFor:
		return (*ForStatement)(n.ptr).Idx1()
	case StmtForIn:
		return (*ForInStatement)(n.ptr).Idx1()
	case StmtForOf:
		return (*ForOfStatement)(n.ptr).Idx1()
	case StmtFuncDecl:
		return (*FunctionDeclaration)(n.ptr).Idx1()
	case StmtIf:
		return (*IfStatement)(n.ptr).Idx1()
	case StmtLabelled:
		return (*LabelledStatement)(n.ptr).Idx1()
	case StmtReturn:
		return (*ReturnStatement)(n.ptr).Idx1()
	case StmtSwitch:
		return (*SwitchStatement)(n.ptr).Idx1()
	case StmtThrow:
		return (*ThrowStatement)(n.ptr).Idx1()
	case StmtTry:
		return (*TryStatement)(n.ptr).Idx1()
	case StmtVarDecl:
		return (*VariableDeclaration)(n.ptr).Idx1()
	case StmtWhile:
		return (*WhileStatement)(n.ptr).Idx1()
	case StmtWith:
		return (*WithStatement)(n.ptr).Idx1()
	}
	return 0
}

func (n *Statement) Unwrap() VisitableNode {
	if n == nil {
		return nil
	}
	switch n.kind {
	case StmtBad:
		return (*BadStatement)(n.ptr)
	case StmtBlock:
		return (*BlockStatement)(n.ptr)
	case StmtBreak:
		return (*BreakStatement)(n.ptr)
	case StmtCase:
		return (*CaseStatement)(n.ptr)
	case StmtCatch:
		return (*CatchStatement)(n.ptr)
	case StmtClassDecl:
		return (*ClassDeclaration)(n.ptr)
	case StmtContinue:
		return (*ContinueStatement)(n.ptr)
	case StmtDebugger:
		return (*DebuggerStatement)(n.ptr)
	case StmtDoWhile:
		return (*DoWhileStatement)(n.ptr)
	case StmtEmpty:
		return (*EmptyStatement)(n.ptr)
	case StmtExpression:
		return (*ExpressionStatement)(n.ptr)
	case StmtFor:
		return (*ForStatement)(n.ptr)
	case StmtForIn:
		return (*ForInStatement)(n.ptr)
	case StmtForOf:
		return (*ForOfStatement)(n.ptr)
	case StmtFuncDecl:
		return (*FunctionDeclaration)(n.ptr)
	case StmtIf:
		return (*IfStatement)(n.ptr)
	case StmtLabelled:
		return (*LabelledStatement)(n.ptr)
	case StmtReturn:
		return (*ReturnStatement)(n.ptr)
	case StmtSwitch:
		return (*SwitchStatement)(n.ptr)
	case StmtThrow:
		return (*ThrowStatement)(n.ptr)
	case StmtTry:
		return (*TryStatement)(n.ptr)
	case StmtVarDecl:
		return (*VariableDeclaration)(n.ptr)
	case StmtWhile:
		return (*WhileStatement)(n.ptr)
	case StmtWith:
		return (*WithStatement)(n.ptr)
	}
	return nil
}
